# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [30]:
import numpy as np

#### Create an array of 10 zeros 

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### Create an array of 10 ones

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Create an array of 10 fives

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### Create an array of the integers from 10 to 50

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

array([10, 14, 18, 22, 26, 30, 34, 38, 42, 46])

#### Create a 3x3 matrix with values ranging from 0 to 8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

array([0.03075386, 0.42870775, 0.68063144, 0.38855701, 0.00731468,
       0.93390479, 0.70227981, 0.34445052, 0.22309968, 0.45545899,
       0.32692485, 0.82372989, 0.44501866, 0.17704038, 0.58454515,
       0.28142691, 0.10656862, 0.71254469, 0.51676049, 0.19545395,
       0.27611728, 0.38312142, 0.50900291, 0.79949961, 0.11970381])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

array([-1.49155005, -0.33886812,  0.39694542,  0.22920124, -0.46912355,
       -1.54636342,  1.32247228,  0.22804939,  0.28311829, -0.79741717,
        0.42169451,  0.16969867,  1.44943954,  0.13965813,  0.27864778,
        1.00724933,  0.97980814, -0.32576689, -0.19172259,  0.91158343,
       -0.31350493,  0.29673087, -1.95303767, -0.14184552,  0.35175282])

#### Create the following matrix:

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99])

#### Create an array of 20 linearly spaced points between 0 and 1:

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [5]:
mat=np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [8]:
mat[:3,1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([ 1,  6, 11, 16, 21])

In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([21, 22, 23, 24, 25])

In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

325

#### Get the standard deviation of the values in mat

7.211102550927978

#### Get the sum of all the columns in mat

In [52]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

#### Flip the array

In [89]:
mat = np.arange(1,26).reshape(5,5)
mat1=np.flip(mat)
np.diagonal(mat1, offset=0)
mat2=np.append(mat, [[1],[2],[3],[4],[5]], axis=1)
print(mat2)
#np.diagonal(mat1)
#type(mat)

[[ 1  2  3  4  5  1]
 [ 6  7  8  9 10  2]
 [11 12 13 14 15  3]
 [16 17 18 19 20  4]
 [21 22 23 24 25  5]]


##### Add row in the matrix

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat2=np.append(mat, [[1,2,3,4,5], axis=0)
print(mat2)

##### Add Column in the matrix


In [93]:
mat = np.arange(1,26).reshape(5,5)
mat2=np.append(mat, [[1],[2],[3],[4],[5]], axis=1)
print(mat2)

[[ 1  2  3  4  5  1]
 [ 6  7  8  9 10  2]
 [11 12 13 14 15  3]
 [16 17 18 19 20  4]
 [21 22 23 24 25  5]]


In [10]:
#Check whether a Numpy array contains a specified row

print([1, 2, 3, 4, 5] in mat.tolist())
print([16, 17, 20, 19, 18] in  mat.tolist())
print([3, 2, 5, -4, 5] in  mat.tolist())
print([11, 12, 13, 14, 15] in  mat.tolist())

True
False
False
True


In [17]:
#most frequent value in numpy array
a=np.array([1,1,1,1,2,3,4,5])
print(a)
print('\n max arg is : ')
print(np.bincount(a).argmax())

[1 1 1 1 2 3 4 5]

 max arg is : 
1


In [18]:
#How to reverse a NumPy array in Python
print(np.flipud(a))


[5 4 3 2 1 1 1 1]


In [ ]:
#Get the minimum value from given matrix 

#Find the number of rows and columns of a given matrix using NumPy 

#Calculate the sum of the diagonal elements of a NumPy array 

#Ways to add row/columns in numpy array 

#Matrix Multiplication in NumPy 

#Convert the matrix into a list 

In [23]:
#1
arr = np.amin(a)
print(arr)

1


In [25]:
#2
print(a.shape)

(8,)


In [32]:
#3
# Finding the diagonal elements of a matrix
newA = np.arange(1,26).reshape(5,5)
diag = np.diagonal(newA)
print("\nDiagonal elements are:")
print(diag)
  
print("\nSum of Diagonal elements is:")
print(sum(diag))


Diagonal elements are:
[ 1  7 13 19 25]

Sum of Diagonal elements is:
65


In [33]:
#4
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
 
# printing initial array
print(ini_array)
 
# Array to be added as column
column_to_be_added = np.array([1, 2, 3])
 
# Adding column to numpy array
result = np.column_stack((ini_array, column_to_be_added))
 
# printing result
print (result)

[[ 1  2  3]
 [45  4  7]
 [ 9  6 10]]
[[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


In [34]:
#5
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])
  
# This will return dot product
res = np.dot(mat1,mat2)
print(res)


[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


In [36]:
#6
print("Sample matrix:")
print(mat)
  
print("Matrix into a single list")
print(list(mat))

Sample matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Matrix into a single list
[array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15]), array([16, 17, 18, 19, 20]), array([21, 22, 23, 24, 25])]


# Great Job!